---
- hosts: all
  become: yes
  tasks:
    - name: Create directory for template deployment
      file:
        path: /home/ansible/lab-templates
        state: directory
        mode: '0755'

    - name: Deploy template file
      template:
        src: /templates-lab/hardened.j2
        dest: /etc/sudoers.d/hardened
        mode: '0440'
        validate: /sbin/visudo -cf %s

    - name: Success Message   
      debug:
        msg: "Setting file permissions success."


